//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuLinTu.Component.MapFoundation.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YuLinTu.Component.MapFoundation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;language&gt;
        ///  &lt;lang1170000&gt;测量&lt;/lang1170000&gt;
        ///  &lt;lang1170001&gt;测量方式:&lt;/lang1170001&gt;
        ///  &lt;lang1170002&gt;单位:&lt;/lang1170002&gt;
        ///  &lt;lang1170003&gt;面积&lt;/lang1170003&gt;
        ///  &lt;lang1170004&gt;长度&lt;/lang1170004&gt;
        ///  &lt;lang1170005&gt;半径&lt;/lang1170005&gt;
        ///  &lt;lang1170006&gt;十进制度&lt;/lang1170006&gt;
        ///  &lt;lang1170007&gt;英尺&lt;/lang1170007&gt;
        ///  &lt;lang1170008&gt;千米&lt;/lang1170008&gt;
        ///  &lt;lang1170009&gt;米&lt;/lang1170009&gt;
        ///  &lt;lang1170010&gt;英里&lt;/lang1170010&gt;
        ///  &lt;lang1170011&gt;海里&lt;/lang1170011&gt;
        ///  &lt;lang1170012&gt;码&lt;/lang1170012&gt;
        ///  &lt;lang1170013&gt;面积: &lt;/lang1170013&gt;
        ///  &lt;lang1170014&gt;长度: &lt;/lang1170014 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string langChs {
            get {
                return ResourceManager.GetString("langChs", resourceCulture);
            }
        }
    }
}
